/**
 * A leaf module on purpose: `scripts/build-redirects.ts` runs under plain node
 * and cannot import anything that reaches `astro:content`, which is what
 * `taxonomy.ts` does. Both sides import this instead, so a tag URL generated by
 * the script and a tag route rendered by the site can never disagree.
 */
export function slugify(value: string): string {
  return value
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
}
