// GENERATED by scripts/build-redirects.ts, do not edit by hand.
//
// Every entry becomes a stub page at build: a meta-refresh with a canonical
// pointing at the target and a visible link, since static hosting cannot issue
// a real 301. Google treats meta-refresh as a redirect and passes the ranking.
export interface Redirect {
  /** Path Ghost served, always with a trailing slash unless it is a file. */
  from: string
  to: string
  /** Why it exists, so a future reader can tell which rules are still needed. */
  note: string
}

export const redirects: Redirect[] = [
  {
    "from": "/author/khaosdoctor/",
    "to": "/",
    "note": "Ghost author archive"
  },
  {
    "from": "/author/lucas-santos/",
    "to": "/",
    "note": "Ghost author archive"
  },
  {
    "from": "/feed/",
    "to": "/rss.xml",
    "note": "Ghost feed path"
  },
  {
    "from": "/fts-fundadores-news/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ganhadores-do-sorteio-de-4k-seguidores/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-abril-de-2021/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-agosto-2021/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-dezembro-de-2020/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-fevereiro-2021/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-janeiro-de-2021/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-julho-2021/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-junho-de-2021/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-marco-de-2021/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-novembro-de-2020/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/giro-de-noticias-outubro-2020/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-1/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-10/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-11-2/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-11/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-13/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-14/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-15/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-16/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-17/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-18/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-19/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-2/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-3/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-4/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-5/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-6/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-7/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-8/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-9/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/ls-news-especial/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-mai-21/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-1/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-10/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-11/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-12/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-2/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-3/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-4/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-5/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-6/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-7/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-8/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/noticias-semanais-9/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/por-essa-surpresa-voce-nao-esperava/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/queria-ter-aprendido-isso-antes/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/rss/",
    "to": "/rss.xml",
    "note": "Ghost feed path"
  },
  {
    "from": "/sitemap-authors.xml",
    "to": "/sitemap-index.xml",
    "note": "Ghost sitemap"
  },
  {
    "from": "/sitemap-pages.xml",
    "to": "/sitemap-index.xml",
    "note": "Ghost sitemap"
  },
  {
    "from": "/sitemap-posts.xml",
    "to": "/sitemap-index.xml",
    "note": "Ghost sitemap"
  },
  {
    "from": "/sitemap-tags.xml",
    "to": "/sitemap-index.xml",
    "note": "Ghost sitemap"
  },
  {
    "from": "/sitemap.xml",
    "to": "/sitemap-index.xml",
    "note": "Ghost sitemap"
  },
  {
    "from": "/sobe-a-semana-ts/",
    "to": "/",
    "note": "newsletter issue"
  },
  {
    "from": "/tag/acr/",
    "to": "/tags/acr/",
    "note": "tag archive"
  },
  {
    "from": "/tag/aks/",
    "to": "/tags/aks/",
    "note": "tag archive"
  },
  {
    "from": "/tag/architecture/",
    "to": "/tags/architecture/",
    "note": "tag archive"
  },
  {
    "from": "/tag/azure-monitor/",
    "to": "/tags/azure-monitor/",
    "note": "tag archive"
  },
  {
    "from": "/tag/azure/",
    "to": "/tags/azure/",
    "note": "tag archive"
  },
  {
    "from": "/tag/backlog-newsletter/",
    "to": "/tags/backlog-newsletter/",
    "note": "tag archive"
  },
  {
    "from": "/tag/blog/",
    "to": "/tags/blog/",
    "note": "tag archive"
  },
  {
    "from": "/tag/bots/",
    "to": "/tags/bots/",
    "note": "tag archive"
  },
  {
    "from": "/tag/career/",
    "to": "/career/",
    "note": "tag became a section"
  },
  {
    "from": "/tag/ci/",
    "to": "/tags/ci/",
    "note": "tag archive"
  },
  {
    "from": "/tag/cloud/",
    "to": "/tags/cloud/",
    "note": "tag archive"
  },
  {
    "from": "/tag/codespaces/",
    "to": "/tags/codespaces/",
    "note": "tag archive"
  },
  {
    "from": "/tag/computing/",
    "to": "/tags/computing/",
    "note": "tag archive"
  },
  {
    "from": "/tag/containerd/",
    "to": "/tags/containerd/",
    "note": "tag archive"
  },
  {
    "from": "/tag/containers/",
    "to": "/tags/containers/",
    "note": "tag archive"
  },
  {
    "from": "/tag/cri-o/",
    "to": "/tags/cri-o/",
    "note": "tag archive"
  },
  {
    "from": "/tag/cri/",
    "to": "/tags/cri/",
    "note": "tag archive"
  },
  {
    "from": "/tag/cryptography/",
    "to": "/tags/cryptography/",
    "note": "tag archive"
  },
  {
    "from": "/tag/databases/",
    "to": "/tags/databases/",
    "note": "tag archive"
  },
  {
    "from": "/tag/deno/",
    "to": "/tags/deno/",
    "note": "tag archive"
  },
  {
    "from": "/tag/development/",
    "to": "/tags/development/",
    "note": "tag archive"
  },
  {
    "from": "/tag/devops/",
    "to": "/tags/devops/",
    "note": "tag archive"
  },
  {
    "from": "/tag/docker/",
    "to": "/tags/docker/",
    "note": "tag archive"
  },
  {
    "from": "/tag/drop/",
    "to": "/tags/drop/",
    "note": "tag archive"
  },
  {
    "from": "/tag/ecmascript/",
    "to": "/tags/ecmascript/",
    "note": "tag archive"
  },
  {
    "from": "/tag/es2020/",
    "to": "/tags/es2020/",
    "note": "tag archive"
  },
  {
    "from": "/tag/events/",
    "to": "/tags/events/",
    "note": "tag archive"
  },
  {
    "from": "/tag/git/",
    "to": "/tags/git/",
    "note": "tag archive"
  },
  {
    "from": "/tag/github/",
    "to": "/tags/github/",
    "note": "tag archive"
  },
  {
    "from": "/tag/golang/",
    "to": "/tags/golang/",
    "note": "tag archive"
  },
  {
    "from": "/tag/grammy/",
    "to": "/tags/grammy/",
    "note": "tag archive"
  },
  {
    "from": "/tag/grpc/",
    "to": "/tags/grpc/",
    "note": "tag archive"
  },
  {
    "from": "/tag/harperdb/",
    "to": "/tags/harperdb/",
    "note": "tag archive"
  },
  {
    "from": "/tag/helm/",
    "to": "/tags/helm/",
    "note": "tag archive"
  },
  {
    "from": "/tag/hipsters/",
    "to": "/tags/hipsters/",
    "note": "tag archive"
  },
  {
    "from": "/tag/history/",
    "to": "/tags/history/",
    "note": "tag archive"
  },
  {
    "from": "/tag/info/",
    "to": "/tags/info/",
    "note": "tag archive"
  },
  {
    "from": "/tag/infra/",
    "to": "/infra/",
    "note": "tag became a section"
  },
  {
    "from": "/tag/jaeger/",
    "to": "/tags/jaeger/",
    "note": "tag archive"
  },
  {
    "from": "/tag/javascript/",
    "to": "/javascript/",
    "note": "tag became a section"
  },
  {
    "from": "/tag/jest/",
    "to": "/tags/jest/",
    "note": "tag archive"
  },
  {
    "from": "/tag/keda/",
    "to": "/tags/keda/",
    "note": "tag archive"
  },
  {
    "from": "/tag/kubernetes/",
    "to": "/tags/kubernetes/",
    "note": "tag archive"
  },
  {
    "from": "/tag/linkerd/",
    "to": "/tags/linkerd/",
    "note": "tag archive"
  },
  {
    "from": "/tag/meetup/",
    "to": "/tags/meetup/",
    "note": "tag archive"
  },
  {
    "from": "/tag/meta/",
    "to": "/meta/",
    "note": "tag became a section"
  },
  {
    "from": "/tag/microservices/",
    "to": "/tags/microservices/",
    "note": "tag archive"
  },
  {
    "from": "/tag/microsservicos/",
    "to": "/tags/microsservicos/",
    "note": "tag archive"
  },
  {
    "from": "/tag/monitor/",
    "to": "/tags/monitor/",
    "note": "tag archive"
  },
  {
    "from": "/tag/news/",
    "to": "/tags/news/",
    "note": "tag archive"
  },
  {
    "from": "/tag/nodejs/",
    "to": "/tags/nodejs/",
    "note": "tag archive"
  },
  {
    "from": "/tag/npm/",
    "to": "/tags/npm/",
    "note": "tag archive"
  },
  {
    "from": "/tag/oci/",
    "to": "/tags/oci/",
    "note": "tag archive"
  },
  {
    "from": "/tag/open-source/",
    "to": "/tags/open-source/",
    "note": "tag archive"
  },
  {
    "from": "/tag/opinion/",
    "to": "/opinion/",
    "note": "tag became a section"
  },
  {
    "from": "/tag/performance/",
    "to": "/tags/performance/",
    "note": "tag archive"
  },
  {
    "from": "/tag/personal/",
    "to": "/tags/personal/",
    "note": "tag archive"
  },
  {
    "from": "/tag/podcasts/",
    "to": "/tags/podcasts/",
    "note": "tag archive"
  },
  {
    "from": "/tag/productivity/",
    "to": "/tags/productivity/",
    "note": "tag archive"
  },
  {
    "from": "/tag/prometheus/",
    "to": "/tags/prometheus/",
    "note": "tag archive"
  },
  {
    "from": "/tag/protobuf/",
    "to": "/tags/protobuf/",
    "note": "tag archive"
  },
  {
    "from": "/tag/react/",
    "to": "/tags/react/",
    "note": "tag archive"
  },
  {
    "from": "/tag/rest/",
    "to": "/tags/rest/",
    "note": "tag archive"
  },
  {
    "from": "/tag/security/",
    "to": "/security/",
    "note": "tag became a section"
  },
  {
    "from": "/tag/series/",
    "to": "/tags/series/",
    "note": "tag archive"
  },
  {
    "from": "/tag/signals/",
    "to": "/tags/signals/",
    "note": "tag archive"
  },
  {
    "from": "/tag/talk/",
    "to": "/tags/talk/",
    "note": "tag archive"
  },
  {
    "from": "/tag/technology/",
    "to": "/tags/technology/",
    "note": "tag archive"
  },
  {
    "from": "/tag/telegram/",
    "to": "/tags/telegram/",
    "note": "tag archive"
  },
  {
    "from": "/tag/tests/",
    "to": "/tags/tests/",
    "note": "tag archive"
  },
  {
    "from": "/tag/theory/",
    "to": "/tags/theory/",
    "note": "tag archive"
  },
  {
    "from": "/tag/threads/",
    "to": "/tags/threads/",
    "note": "tag archive"
  },
  {
    "from": "/tag/tips/",
    "to": "/tags/tips/",
    "note": "tag archive"
  },
  {
    "from": "/tag/tools/",
    "to": "/tags/tools/",
    "note": "tag archive"
  },
  {
    "from": "/tag/typescript/",
    "to": "/typescript/",
    "note": "tag became a section"
  },
  {
    "from": "/tag/video/",
    "to": "/tags/video/",
    "note": "tag archive"
  },
  {
    "from": "/tag/vim/",
    "to": "/tags/vim/",
    "note": "tag archive"
  },
  {
    "from": "/tag/virtual-machines/",
    "to": "/tags/virtual-machines/",
    "note": "tag archive"
  },
  {
    "from": "/tag/vpn/",
    "to": "/tags/vpn/",
    "note": "tag archive"
  },
  {
    "from": "/tag/vscode/",
    "to": "/tags/vscode/",
    "note": "tag archive"
  },
  {
    "from": "/tag/workshop/",
    "to": "/tags/workshop/",
    "note": "tag archive"
  }
]
